# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: html-deployment
#   labels:
#     app: html
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: html
#   template:
#     metadata:
#       labels:
#         app: html
#     spec:
#       containers:
#       - name: nginx
#         image: nginx:alpine
#         volumeMounts:
#         - name: html-volume
#           mountPath: /usr/share/nginx/html
#       volumes:
#       - name: html-volume
#         configMap:
#           name: html-config
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: html-config
# data:
#   index.html: |
#     <!DOCTYPE html>
#     <html>
#     <head><title>Hello</title></head>
#     <body><h1>Hello, Hariommmm</h1></body>
#     </html>
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: html-service
# spec:
#   selector:
#     app: html
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
#   type: NodePort




apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-deployment
  labels:
    app: html
spec:
  replicas: 1
  selector:
    matchLabels:
      app: html
  template:
    metadata:
      labels:
        app: html
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        hostPath:
          path: ./index.html
          type: File
---
apiVersion: v1
kind: Service
metadata:
  name: html-service
spec:
  selector:
    app: html
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
