apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-deployment
  labels:
    app: html
spec:
  replicas: 1
  selector:
    matchLabels:
      app: html
  template:
    metadata:
      labels:
        app: html
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: html-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: html-config
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      <title>Hospital Food Management System</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          background: #f1f1f1;
          margin: 0;
          padding: 0;
        }
        header {
          background: #0077b6;
          color: white;
          padding: 20px;
          text-align: center;
        }
        main {
          padding: 20px;
        }
        section {
          background: white;
          padding: 20px;
          margin-bottom: 20px;
          border-radius: 8px;
          box-shadow: 0 2px 6px rgba(0,0,0,0.1);
        }
        h2 {
          color: #023e8a;
        }
        label {
          display: block;
          margin-top: 10px;
        }
        input, select, textarea {
          width: 100%;
          padding: 8px;
          margin-top: 5px;
          border-radius: 4px;
          border: 1px solid #ccc;
        }
        button {
          margin-top: 15px;
          padding: 10px 15px;
          background: #0077b6;
          color: white;
          border: none;
          border-radius: 5px;
          cursor: pointer;
        }
        button:hover {
          background: #005f87;
        }
      </style>
    </head>
    <body>
      <header>
        <h1>Hospital Food Management System</h1>
      </header>
      <main>
        <section>
          <h2>Patient Meal Order</h2>
          <form>
            <label for="patient-name">Patient Name:</label>
            <input type="text" id="patient-name" required>

            <label for="patient-id">Patient ID:</label>
            <input type="text" id="patient-id" required>

            <label for="meal-type">Meal Type:</label>
            <select id="meal-type" required>
              <option value="breakfast">Breakfast</option>
              <option value="lunch">Lunch</option>
              <option value="dinner">Dinner</option>
            </select>

            <label for="diet-type">Diet Type:</label>
            <select id="diet-type">
              <option value="regular">Regular</option>
              <option value="diabetic">Diabetic</option>
              <option value="low-sodium">Low Sodium</option>
              <option value="vegan">Vegan</option>
            </select>

            <label for="remarks">Special Instructions:</label>
            <textarea id="remarks" rows="3"></textarea>

            <button type="submit">Submit Order</button>
          </form>
        </section>

        <section>
          <h2>Admin Panel (Sample)</h2>
          <p>Future integration for viewing and managing all meal orders.</p>
          <button>View Today's Orders</button>
          <button>Generate Nutrition Report</button>
        </section>
      </main>
    </body>
    </html>

---
apiVersion: v1
kind: Service
metadata:
  name: html-service
spec:
  selector:
    app: html
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort




# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: html-deployment
#   labels:
#     app: html
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: html
#   template:
#     metadata:
#       labels:
#         app: html
#     spec:
#       containers:
#       - name: nginx
#         image: nginx:alpine
#         volumeMounts:
#         - name: html-volume
#           mountPath: /usr/share/nginx/html
#       volumes:
#       - name: html-volume
#         hostPath:
#           path: ./index.html
#           type: File
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: html-service
# spec:
#   selector:
#     app: html
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
#   type: NodePort
