apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-deployment
  labels:
    app: html
spec:
  replicas: 1
  selector:
    matchLabels:
      app: html
  template:
    metadata:
      labels:
        app: html
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: html-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: html-config
data:
  index.html: |
   <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>Hospital Food Management System</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          margin: 20px;
          background: #f4f4f4;
        }
        h2 {
          color: #333;
        }
        .section {
          background: white;
          padding: 20px;
          margin-bottom: 30px;
          border-radius: 8px;
          box-shadow: 0 0 10px rgba(0,0,0,0.1);
        }
        input, select, button {
          padding: 8px;
          margin: 8px 0;
          width: 100%;
          box-sizing: border-box;
        }
        table {
          width: 100%;
          border-collapse: collapse;
          margin-top: 10px;
        }
        table, th, td {
          border: 1px solid #ccc;
        }
        th, td {
          padding: 10px;
          text-align: left;
        }
      </style>
    </head>
    <body>

      <div class="section">
        <h2>Order Food</h2>
        <form id="orderForm">
          <label for="patientName">Patient Name:</label>
          <input type="text" id="patientName" required />

          <label for="roomNumber">Room Number:</label>
          <input type="text" id="roomNumber" required />

          <label for="foodItem">Select Food Item:</label>
          <select id="foodItem" required>
            <option value="Rice">Rice</option>
            <option value="Bread">Bread</option>
            <option value="Soup">Soup</option>
            <option value="Salad">Salad</option>
          </select>

          <label for="quantity">Quantity:</label>
          <input type="number" id="quantity" min="1" required />

          <button type="submit">Place Order</button>
        </form>
      </div>

      <div class="section">
        <h2>Patient Orders</h2>
        <table id="ordersTable">
          <thead>
            <tr>
              <th>Patient Name</th>
              <th>Room</th>
              <th>Food Item</th>
              <th>Quantity</th>
            </tr>
          </thead>
          <tbody></tbody>
        </table>
      </div>

      <div class="section">
        <h2>Food Inventory</h2>
        <table id="inventoryTable">
          <thead>
            <tr>
              <th>Food Item</th>
              <th>Available Quantity</th>
            </tr>
          </thead>
          <tbody>
            <tr><td>Rice</td><td id="inv-Rice">100</td></tr>
            <tr><td>Bread</td><td id="inv-Bread">100</td></tr>
            <tr><td>Soup</td><td id="inv-Soup">100</td></tr>
            <tr><td>Salad</td><td id="inv-Salad">100</td></tr>
          </tbody>
        </table>
      </div>

      <script>
        const orderForm = document.getElementById('orderForm');
        const ordersTable = document.querySelector('#ordersTable tbody');

        const inventory = {
          Rice: 100,
          Bread: 100,
          Soup: 100,
          Salad: 100
        };

        orderForm.addEventListener('submit', function(e) {
          e.preventDefault();

          const patientName = document.getElementById('patientName').value;
          const roomNumber = document.getElementById('roomNumber').value;
          const foodItem = document.getElementById('foodItem').value;
          const quantity = parseInt(document.getElementById('quantity').value);

          if (inventory[foodItem] >= quantity) {
            // Reduce inventory
            inventory[foodItem] -= quantity;
            document.getElementById('inv-' + foodItem).innerText = inventory[foodItem];

            // Add to order list
            const row = document.createElement('tr');
            row.innerHTML = `
              <td>${patientName}</td>
              <td>${roomNumber}</td>
              <td>${foodItem}</td>
              <td>${quantity}</td>
            `;
            ordersTable.appendChild(row);

            // Reset form
            orderForm.reset();
          } else {
            alert(`Not enough ${foodItem} in inventory.`);
          }
        });
      </script>

    </body>
    </html>


---
apiVersion: v1
kind: Service
metadata:
  name: html-service
spec:
  selector:
    app: html
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort




# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: html-deployment
#   labels:
#     app: html
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: html
#   template:
#     metadata:
#       labels:
#         app: html
#     spec:
#       containers:
#       - name: nginx
#         image: nginx:alpine
#         volumeMounts:
#         - name: html-volume
#           mountPath: /usr/share/nginx/html
#       volumes:
#       - name: html-volume
#         hostPath:
#           path: ./index.html
#           type: File
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: html-service
# spec:
#   selector:
#     app: html
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
#   type: NodePort
